//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANX.Framework.VisualStudio.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PackageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PackageResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ANX.Framework.VisualStudio.Resources.PackageResources", typeof(PackageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add build reference ähnelt.
        /// </summary>
        public static string AddBuildReferenceWindowTitle {
            get {
                return ResourceManager.GetString("AddBuildReferenceWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The assembly &quot;{0}&quot; will be redirected to a custom assembly of the ANX Visual Studio extension. ähnelt.
        /// </summary>
        public static string AnxFrameworkAssembliesRedirected {
            get {
                return ResourceManager.GetString("AnxFrameworkAssembliesRedirected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Asset Name ähnelt.
        /// </summary>
        public static string AssetName {
            get {
                return ResourceManager.GetString("AssetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name that will be used to reference this content at runtime. ähnelt.
        /// </summary>
        public static string AssetNameDescription {
            get {
                return ResourceManager.GetString("AssetNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browse ANX Framework directory ähnelt.
        /// </summary>
        public static string BrowseAnxFrameworkDirectory {
            get {
                return ResourceManager.GetString("BrowseAnxFrameworkDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browse output directory ähnelt.
        /// </summary>
        public static string BrowseOutputDirectory {
            get {
                return ResourceManager.GetString("BrowseOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Building ähnelt.
        /// </summary>
        public static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Build references ähnelt.
        /// </summary>
        public static string BuildReferences {
            get {
                return ResourceManager.GetString("BuildReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Content ähnelt.
        /// </summary>
        public static string ConfigurableContentProjectSettings {
            get {
                return ResourceManager.GetString("ConfigurableContentProjectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Content Importer ähnelt.
        /// </summary>
        public static string ContentImporter {
            get {
                return ResourceManager.GetString("ContentImporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The importer used for this piece of content during the build process. ähnelt.
        /// </summary>
        public static string ContentImporterDescription {
            get {
                return ResourceManager.GetString("ContentImporterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Content Processor ähnelt.
        /// </summary>
        public static string ContentProcessor {
            get {
                return ResourceManager.GetString("ContentProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The processor used for this piece of content during the build process. ähnelt.
        /// </summary>
        public static string ContentProcessorDescription {
            get {
                return ResourceManager.GetString("ContentProcessorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Framework ähnelt.
        /// </summary>
        public static string ContentProjectSettings {
            get {
                return ResourceManager.GetString("ContentProjectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Content root ähnelt.
        /// </summary>
        public static string ContentRoot {
            get {
                return ResourceManager.GetString("ContentRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Folder in the target project that will contain the compiled assets. ähnelt.
        /// </summary>
        public static string ContentRootDescription {
            get {
                return ResourceManager.GetString("ContentRootDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Debugging ähnelt.
        /// </summary>
        public static string Debugging {
            get {
                return ResourceManager.GetString("Debugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install other frameworks... ähnelt.
        /// </summary>
        public static string InstallOtherFrameworks {
            get {
                return ResourceManager.GetString("InstallOtherFrameworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://go.microsoft.com/fwlink/?LinkID=224419 ähnelt.
        /// </summary>
        public static string InstallOtherFrameworksFWLink {
            get {
                return ResourceManager.GetString("InstallOtherFrameworksFWLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (None) ähnelt.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The processor&apos;s {0} property is set to this value before the asset is built. ähnelt.
        /// </summary>
        public static string ParameterDefaultDescription {
            get {
                return ResourceManager.GetString("ParameterDefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This instance does not support ResetValue. Use CanResetValue before calling this method to see if it is supported. ähnelt.
        /// </summary>
        public static string PropertyDescriptorResetNotSupported {
            get {
                return ResourceManager.GetString("PropertyDescriptorResetNotSupported", resourceCulture);
            }
        }
    }
}
