//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentBuilder {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContentBuilder.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die could not find file &apos;{0}&apos; to import. skipping. ähnelt.
        /// </summary>
        internal static string FileNotFound_Skipping {
            get {
                return ResourceManager.GetString("FileNotFound_Skipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finished loading assemblies. ähnelt.
        /// </summary>
        internal static string FinishedLoadingAssemblies {
            get {
                return ResourceManager.GetString("FinishedLoadingAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finished loading build items. ähnelt.
        /// </summary>
        internal static string FinishedLoadingBuildItems {
            get {
                return ResourceManager.GetString("FinishedLoadingBuildItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;{0}&quot; missed a content importer, using &quot;{1}&quot;. ähnelt.
        /// </summary>
        internal static string MissedImporterUsingDefault {
            get {
                return ResourceManager.GetString("MissedImporterUsingDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;{0}&quot; missed a content processor, using &quot;{1}&quot;. ähnelt.
        /// </summary>
        internal static string MissedProcessorUsingDefault {
            get {
                return ResourceManager.GetString("MissedProcessorUsingDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No items specified. Closing application. ähnelt.
        /// </summary>
        internal static string NoItemsSpecified {
            get {
                return ResourceManager.GetString("NoItemsSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Items to build. ähnelt.
        /// </summary>
        internal static string NoItemsToBuild {
            get {
                return ResourceManager.GetString("NoItemsToBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file path represented by the parameter &quot;{0}&quot; is invalid. ähnelt.
        /// </summary>
        internal static string ParameterPathIsInvalid {
            get {
                return ResourceManager.GetString("ParameterPathIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die couldn&apos;t set target platform &quot;{0}&quot; ähnelt.
        /// </summary>
        internal static string PlatformNotSetable {
            get {
                return ResourceManager.GetString("PlatformNotSetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project doesn&apos;t contain configurations. ähnelt.
        /// </summary>
        internal static string ProjectDoesntContainConfiguration {
            get {
                return ResourceManager.GetString("ProjectDoesntContainConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The assembly {0} has been redirected to &quot;{1}&quot;. ähnelt.
        /// </summary>
        internal static string RedirectedAssembly {
            get {
                return ResourceManager.GetString("RedirectedAssembly", resourceCulture);
            }
        }
    }
}
